### PR TITLE
[PHEx] Add firefox support

### PR DESCRIPTION
**Pull request by afkvido**
hope [this guide](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions) will be good

### CODE REVIEW

**Comment by afkvido** [comment]
ffs it didnt work

**Comment by afkvido** [comment]
@Erisfiregamer1 @donaldli2020 

alright y'all, how does this look?
don't merge please, i'll bother with all the releasing myself.

**Comment by afkvido** [comment]
gtg, i'll implement the force thing on InfiniteZero soon

**Comment by afkvido** [comment]
@Erisfiregamer1 @donaldli2020 are yall dead or smth? ig ill just begin without yalls

**Comment by afkvido** [comment]
shit i rebased when i didnt mean to

**Comment by afkvido** [comment]
anyways imma get ready to release lol

**Comment by afkvido** [comment]
gonna merge then it'll be time for some RELEASE MAKING **fml**

**Comment by Erisfiregamer1** [comment]
I was sleeping! :heck:
Looks good though.

**Comment by afkvido** [comment]
xd

**Pull request merged**
