### PR TITLE
indent this properly

### PR DESCRIPTION
**Pull request by donaldli2020**

### CODE REVIEW

**Review by afkvido — APPROVED** [review]
sure

**Comment by afkvido** [comment]
about https://github.com/ProdigyPNP/ProdigyMathGameHacking/pull/21/commits/5574054e429c9547ee475bff60d87cd7c59c7691, try setting up GPG properly

**Comment by donaldli2020** [comment]
> about [5574054](https://github.com/ProdigyPNP/ProdigyMathGameHacking/commit/5574054e429c9547ee475bff60d87cd7c59c7691), try setting up GPG properly

i used vscode

**Comment by donaldli2020** [comment]
and gh desktop

**Comment by donaldli2020** [comment]
on a windows 7

**Comment by donaldli2020** [comment]
windows be like 8,10,11 but i used 7

**Comment by afkvido** [comment]
ok

**Pull request merged**
