### PR TITLE
Disable Collision

### PR DESCRIPTION
**Pull request by ProdigyPNPEnthusiast**
Signed-off-by: ProdigyPNPEnthusiast <113353341+ProdigyPNPEnthusiast@users.noreply.github.com>

### CODE REVIEW

**Comment by afkvido** [comment]
Pretty good. Is there a way to make this toggleable though?

**Comment by ProdigyPNPEnthusiast** [comment]
I don't think so

**Comment by afkvido** [comment]
Hold up I just had an idea.

**Comment by ProdigyPNPEnthusiast** [comment]
What?

**Comment by afkvido** [comment]
Actually, during testing, this seems to actually not work. Whatever, not like anyone would need the barriers back.

**Comment by ProdigyPNPEnthusiast** [comment]
I think it deactivates when you go off the screen. Just use it again.

**Review by afkvido — APPROVED** [review]
lgtm tbh.

**Comment by afkvido** [comment]
> I think it deactivates when you go off the screen. Just use it again.

In that case, we should use a similar approach as with Toggle Click Teleporting.

**Pull request merged**
