### PR TITLE
!!! PHEx Mv3 (Awaiting review and final touches)

### PR DESCRIPTION
**Pull request by donaldli2020**
- [x] **Fix the fucking CSP removal**
- [x] Does it work? Well we had to do something else.
-
- [x] **Fix the fucking script injection**
- [x] ***Does it work???***
-
- [x] ~~Once CSP removal is done then add the redirect for** `/load-game.min.js`~~ Alternative found
- [x] Does it work? Yes, we just use HTML IDs to change the splash screen text.:
- 
- [x] Fix the script. (DONE by afkvido)
- [x] Remove the file `./.github/workflows/removeonmerge.yml`.
- [X] cleanup

## Does this look good?
- [ ] @Erisfiregamer1 
- [ ] @donaldli2020 
- [x] @afkvido

# Releasing
First we wait until the Alphas have checked the boxes.
- [ ] Sign the CRX
- [ ] Make a release on GitHub Releases
- [ ] Make a release on the Microsoft Addons Store
- [ ] Make a release on the Mozilla Addons Store
- [ ] Make a release on the Chrome Web Store
- [ ] Make a release on the Opera Addons Store

### CODE REVIEW

**Comment by donaldli2020** [comment]
> * Remotely hosted code is no longer allowed; an extension can only execute JavaScript that is included within its package.

this is big

**Comment by afkvido** [comment]
7f352a20eedd950107f691ed20c3f6c5dda42a77

MV3 - At least we can block Prodigy's code!

This took me 3 collective hours of research, coding, and getting the fucking thing to work.

And yes, I signed the CRX.

**Comment by afkvido** [comment]
**Remotely hosted code is no longer allowed; an extension can only execute JavaScript that is included within its package.**

I'm pretty sure that the migration guide said that we can still use `fetch()` every now and then.

**Comment by Erisfiregamer1** [comment]
Created a tracking issue. Also, updated to base branch.

**Comment by Erisfiregamer1** [comment]
I'm going to figure out some way to load the **game.min.js** file from PHEx so we don't have to deal with P-NP or any derivative. This would *probably* break Infinite Zero, though.

**Comment by afkvido** [comment]
@Erisfiregamer1 New idea for infinite zero:

Infinite Zero's server will host a JavaScript file which will do this:

```js
// Load the cheat menu
(async () => {
	eval(await (await fetch("The random URL that Infintie Zero decided")).text())
})();
```

And it'll just return the P-NP URL in the thing. 


ADITIONALLY, we could use URL attributes to force Infinite Zero to use a specific URL:

For example: ``http://infinitezero.net/domain?force=https://p-np.prodigypnp.repl.co`` will return
```js
// Load the cheat menu
(async () => {
	eval(await (await fetch("https://p-np.prodigypnp.repl.co/game.min.js")).text())
})();
```

**Comment by afkvido** [comment]
We should take a look at [this](https://github.com/ProdigyAPI/ProdigyXLoader/blob/master/src/contentScript.js) and do something similar.

**Comment by afkvido** [comment]
Well... I got it to work.

**Kinda.**

So you'd have to wait until the console complains about an unsafe inline script, then you paste this into the console.


```js
// Load the gamefile
(async () => {
	eval(await (await fetch("https://p-np.prodigypnp.repl.co/game.min.js")).text())
})()
```


**AND IT WORKED.**
The game actually loaded
The menu did too, and the hacks WORK.

**Comment by afkvido** [comment]
So i gave it a fucking SHA256 Hash... and guess what?


**The same FUCKING AAAAAAAAAA**




Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'wasm-unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-ltZpBGBohNR56PwXDlTiKH7xhDGmuH3R07GvNqP6C3I='), or a nonce ('nonce-...') is required to enable inline execution.

(anonymous) @ disableIntegrity.js:59

**Comment by afkvido** [comment]
Screen Shot 2022-07-09 at 1 26 17 AM

like uhhh hello???? here's my hash?

**Comment by afkvido** [comment]
I'm done with PHEx MV3 for the night, see you all soon.

**Comment by Erisfiregamer1** [comment]
Well, shit. Only ProdigyX has a CSP bypass method- and it's in their obfuscated code! Woo!

**Comment by Erisfiregamer1** [comment]
Have we gotten anywhere with CSP?

**Comment by afkvido** [comment]
So I was away for a week, doing stuff outdoors. Let's see...

**Comment by afkvido** [comment]
> Well, shit. Only ProdigyX has a CSP bypass method- and it's in their obfuscated code! Woo!

**bruh**

**Comment by Erisfiregamer1** [comment]
The tracking issue is High, so promoting.

**Comment by afkvido** [comment]
I'ts incomplete...
It seems as if this has done literally nothing. We need more fine-tunin

**Comment by Erisfiregamer1** [comment]
oops I was trying to update

**Comment by afkvido** [comment]
xd

**Comment by Erisfiregamer1** [comment]
@afkvido I have NO IDEA how to resolve these >:(

**Comment by donaldli2020** [comment]
lmao

**Comment by afkvido** [comment]
> @afkvido I have NO IDEA how to resolve these >:(

Ill do a lil resolving

**Comment by afkvido** [comment]
Much better

**Comment by Erisfiregamer1** [comment]
@afkvido We need to stop the cheatGUI conflicts... maybe make them autoupdate AFTER MV3 to mitigate this or have a github bot automatically update it for each branch?

**Comment by afkvido** [comment]
We could manually disable it through the Actions menu

**Comment by Erisfiregamer1** [comment]
Think we're ready? Does it work??
Let me test it.

**Comment by afkvido** [comment]
Does it work?

**Comment by afkvido** [comment]
imma test

**Comment by afkvido** [comment]
Screen Shot 2022-07-25 at 9 24 36 PM

@Erisfiregamer1 LMAO what did you do

**Comment by Erisfiregamer1** [comment]
> Screen Shot 2022-07-25 at 9 24 36 PM
> 
> @Erisfiregamer1 LMAO what did you do

It looks like a bug in the hash code, which I didn't touch- don't point at me.

**Comment by Erisfiregamer1** [comment]
just disabling for now...
if you get it working reenable

**Comment by afkvido** [comment]
@Erisfiregamer1 seems like a bit of a mess

**Comment by afkvido** [comment]
Well there was a bit of a mess so i kinda uhh reset some stuff, time to get back to smth

**Comment by Erisfiregamer1** [comment]
It has to be https://infinitezero.net/domain and not /eval

**Comment by afkvido** [comment]
> It has to be https://infinitezero.net/domain and not /eval

Then it must be `fetch(https://infinitezero.net/domain);` 
(thats not the full command, some more is needed to get it to work.

**Comment by afkvido** [comment]
```js
(await (await fetch("https://infinitezero.net/domain")).text()).valueOf();
```

THIS WORKS PERFECTLY.
Now, for the CSP...

**Comment by afkvido** [comment]
> It looks like a bug in the hash code, which I didn't touch- don't point at me.

@Erisfiregamer1 Ok sorry that was some shitcode in the infinite zero implementation.

**Comment by afkvido** [comment]
I've fixed swal/sweetalert2 not loading because manifest v3 doesnt like `eval()` or `Function()`.

# TIME FOR NO-CSP YALL LETS DO IT

**Comment by afkvido** [comment]
Screen Shot 2022-07-26 at 8 51 29 PM

Fucking opera addons moderator go fuck a horse @operasoftware

**Comment by Erisfiregamer1** [comment]
@afkvido The service worker isnt loaded, maybe fixing ***that*** would do it?

**Comment by Erisfiregamer1** [comment]
Nope. it's loading now but before it wasnt??

**Comment by afkvido** [comment]
It didn't fix?

**Comment by Erisfiregamer1** [comment]
Nope. What the [FIFTY PERCENT OFF] is going on here??
I can't find ANYTHING to solve this!

**Comment by afkvido** [comment]
I dont even know bro. this is so scuffed

**Comment by afkvido** [comment]
Fuck i gotta merge

**Comment by afkvido** [comment]
Mess is cleaned up. BACK TO NO-CSP.

**Comment by Erisfiregamer1** [comment]
yeah no I know nothing about this.

**Comment by afkvido** [comment]
One day, one day.

**Comment by afkvido** [comment]
Have we tried capitalizing `Content-Security-Policy` insetead of `content-security-policy`?

Imma try rn, i swear if this works...

**Comment by afkvido** [comment]
not that it worked.

**Comment by afkvido** [comment]
```js
(async () => {
	eval(await (await fetch("https://infinitezero.net/eval")).text())
})()
```

Pasting this in the console works, but that's manual... and too inconvinient for most PHEx users (who are in fact, monkeys, who don't know how to use the chrome console)

**Comment by afkvido** [comment]
I have an idea.... using this as a content script.... i don't know though...

**Comment by afkvido** [comment]
Screen Shot 2022-08-02 at 1 56 35 AM
I HAD SUCH A GOOD RUN BUT **THIS** HAPPENED

**Comment by hostedposted** [comment]
How have you not finished this yet? It's not that hard

**Comment by afkvido** [comment]
> How have you not finished this yet? It's not that hard

@hostedposted 
For some reason CSP removal doesn't work.
Unless you're gonna help us, I don't see why it's so easy.

**Comment by hostedposted** [comment]
https://github.com/ProdigyPNP/ProdigyMathGameHacking/blob/17449353d6c61d1c4691ecc7394a7389f678689b/PHEx/src/background.js#L17

**Comment by hostedposted** [comment]
Why did you never use the ``h`` in ``hosts``?

**Comment by hostedposted** [comment]
Your Welcome

**Comment by afkvido** [comment]
i will try right now. if this works, thank you <3. if it does work, ill remove the message in #server-announcements regarding prodigyx

**Comment by afkvido** [comment]
Screen Shot 2022-08-02 at 7 54 29 PM

**Comment by afkvido** [comment]
idk whats going on anymore

**Comment by afkvido** [comment]
I don't **see** any Content-Security-Policy headers in the Network stack

**Comment by hostedposted** [comment]
> Screen Shot 2022-08-02 at 7 54 29 PM

I thought you said it was a csp error.



> ~I don't **see** any Content-Security-Policy headers in the Network stack~
> 
> nevermind. What the [FIFITY PERCENT OFF] is going on here? Am i just sped?

Yeah because CSP is being blocked.

The error you saw means you're executing an inline script. Which is not allowed. MV3 restricts adding a script element with raw JavaScript in it to a tab, from an extension.

**Comment by Erisfiregamer1** [comment]
Then how do we load the script?
(hostedposted please help us god we have no idea how to do this we're all giving up)

**Comment by afkvido** [comment]
> The error you saw means you're executing an inline script. Which is not allowed. MV3 restricts adding a script element with raw JavaScript in it to a tab, from an extension.

@hostedposted Isn't that the Scripting API that well, never worked?

**Comment by Erisfiregamer1** [comment]
Note to self: MERGE THE PRIVATE FORK CODE WHEN YOU GET THE DAMN CHANCE.

**Comment by afkvido** [comment]
Why the hell do you have a private fork?

**Comment by Erisfiregamer1** [comment]
**disableIntegrityV2 is in.**
This is a modified version of an older background.js capable of loading game.min.js (with errors).
Thank you hostedposted, absolute chad

**Comment by Erisfiregamer1** [comment]
> Why the hell do you have a private fork?

hosted might not have wanted me to merge the code in before I removed all the ProdigyX stuff from it

**Comment by afkvido** [comment]
Alright.

**Comment by afkvido** [comment]
Thanks @hostedposted! Removing the #server-announcements thing now.

**Comment by afkvido** [comment]
@Erisfiregamer1 Y'know what disableintegrity v2 is missing? A version checker.

Note to self: add the version checker

**Comment by Erisfiregamer1** [comment]
Almost done, this is the last check before I sign off

**Comment by Erisfiregamer1** [comment]
annnnnd I'm done here, @afkvido it's your turn to figure this mess out.
Godspeed.

**Comment by afkvido** [comment]
What the **FUCK happened to the Manifest**

**Comment by afkvido** [comment]
Ty @Erisfiregamer1 for fixing it

**Comment by afkvido** [comment]
Full speed ahead other than a couple things but yea :)

**Comment by afkvido** [comment]
Still gonna remove the autobuild later, but for now, here's how you autobuild.

**Comment by Erisfiregamer1** [comment]
can we remove DeepScan?

**Review by Erisfiregamer1 — COMMENTED** [review]
Just going to point this out: disableIntegrityV2 was literally just a modified version of background.js from commit 40b12de1b9d03a142cb05c550f86f37f65d0a4a4. @afkvido How did you MISS this??

**Comment by afkvido** [comment]
@Erisfiregamer1 I was confused when using ProdigyX's method of document events... kinda made me to decide "fuck this, i won't bother".

**Comment by afkvido** [comment]
> can we remove DeepScan?

bet

**Comment by Erisfiregamer1** [comment]
k

**Comment by afkvido** [comment]
image

This *would* be a legit error, except it's an extension, so no.

Anyway that one I'll find a way to circumvent

**Comment by afkvido** [comment]
Test it yourself, BUT FUCK YEEEAHHHH IT WORKS!!!!

**Comment by Erisfiregamer1** [comment]
Let me test it. WAIT FOR MY REVIEW.

**Comment by afkvido** [comment]
BET

**Review by Erisfiregamer1 — APPROVED** [review]
Oh. My. God.
After all these months, after ALL THE FUCKING SUFFERING, after hosted's help... we've done it. ***MV3 is functioning.***
Special thanks to:
- hostedposted, for helping us a lot
- Svido for finally getting it to work and also doing their best to finish it
- Everyone else who contributed.
I refuse to wait. LGTM

**Comment by afkvido** [comment]
FUCK YEAH!!!!!!

**Comment by afkvido** [comment]
WOOOOo

**Comment by afkvido** [comment]
I'll start signing, releasing, etc.

**Comment by Erisfiregamer1** [comment]
You do that- I'll ensure that the P-NP servers on my network stay updated if need be.
DAMNIT so much work went into this. THANK GOD it's over.

**Comment by afkvido** [comment]
BET BROTHER

**Review by Erisfiregamer1 — COMMENTED** [review]
Why didn't I think of this? (commit: THIS WORKED ONG)

**Comment by afkvido** [comment]
xd

**Pull request merged**
