### PR TITLE
ugly arrows

### PR DESCRIPTION
**Pull request by donaldli2020**
>

### CODE REVIEW

**Comment by donaldli2020** [comment]
i still dont have write access

**Comment by afkvido** [comment]
> i still dont have write access

i thought i gave you write acess? 1sec imma test your code before i merge

**Comment by donaldli2020** [comment]
image

**Comment by afkvido** [comment]
dont merge yet please, i did give you write access tho

**Comment by donaldli2020** [comment]
checking... only 420420696969 checks left!

**Comment by afkvido** [comment]
yes. gimme a sec tho..... i have a better idea.

**Comment by afkvido** [comment]
alr! this seems good. it's still the arrow, just a lil bit smaller

**Comment by donaldli2020** [comment]
it worked without defining the dimensions

**Review by afkvido — APPROVED** [review]

**Review by donaldli2020 — COMMENTED** [review]
lgtm

**Comment by afkvido** [comment]
yayy :)

**Pull request merged**
